package luis.madrid.inmagina;

import com.google.gson.Gson;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Luis' at '22/04/17 10:54' with Gradle 2.14.1
 *
 * @author Luis, @date 22/04/17 10:54
 */
public class Inmagina {
	public static void main(String[] args) {
		final Gson gson = new Gson();
		// original object instantiation
		ModelObject modelObject = new ModelObject("myname", 12, true, 2.3);
		System.out.println("toJson ---");
		System.out.println("Original Java object : " + modelObject);
		// converting an object to json object
		String json = gson.toJson(modelObject);
		System.out.println("Converted JSON string is : " + json);

		System.out.println("fromJson----");
		// getting object from json representation
		System.out.println("Original JSON string is : " + json);
		// converting json to object
		ModelObject modelObject1 = gson.fromJson(json, ModelObject.class);
		System.out.println("Converted Java object : " + modelObject1);
	}
}
