/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Luis' at '22/04/17 10:54' with Gradle 2.14.1
 *
 * @author Luis, @date 22/04/17 10:54
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
